version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - '$JELLYFIN_PATH/config:/config'
      - '$JELLYFIN_PATH/cache:/cache'
      - '$JELLYFIN_DATA/media:/media:ro'
    environment:
      - LETSENCRYPT_HOST
      - VIRTUAL_HOST
      - TRUSTED_PROXIES
      - OVERWRITEPROTOCOL
    restart: unless-stopped
    networks: ["net"]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
        
networks:
    net:
      external: true