version: "3.7"

services:
    db:
        image: postgres:14
        restart: always
        environment:
            - POSTGRES_USER=gitea
            - POSTGRES_PASSWORD=gitea
            - POSTGRES_DB=gitea
        networks:
            - net
        volumes:
            - GiteaDB:/var/lib/postgresql/data

    Gitea:
        image: "gitea/gitea:latest-rootless"

        environment:
            - USER
            - USER_UID
            - USER_GID
            - GITEA__APP_NAME
            - GITEA__RUN_MODE
            - GITEA__server__LOCAL_ROOT_URL
            - USER_UID=1000
            - USER_GID=1000
            - GITEA__database__DB_TYPE=postgres
            - GITEA__database__HOST=db:5432
            - GITEA__database__NAME=gitea
            - GITEA__database__USER=gitea
            - GITEA__database__PASSWD=gitea
            - DOMAIN=${URL}
            - SSH_DOMAIN=${URL}
            - DISABLE_REGISTRATION=true
            - VIRTUAL_HOST=${URL}
            - VIRTUAL_PORT=3000
            - LETSENCRYPT_HOST=${URL}
            - LETSENCRYPT_EMAIL=geraldprendi18@gmail.com
        
        volumes:
            - GiteaData:/var/lib/gitea
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"

        restart: always
        networks:
            - net
        depends_on:
            - db
        ports:
            - 2222:2222
            - 3000:3000
        labels:
            - "com.centurylinklabs.watchtower.enable=true"

volumes:
    GiteaData:
        driver_opts:
            type: nfs
            o: bind
            device: /mnt/mem/cloud/gitserver/gitea
    GiteaDB:
        driver_opts:
            type: nfs
            o: bind
            device: /mnt/mem/cloud/gitserver/db

networks:
    net:
        external: true
