version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - LETSENCRYPT_HOST
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - OVERWRITEPROTOCOL
    volumes:
      - config:/config
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - net
    restart: unless-stopped

volumes:
  config:
    driver_opts:
      type: nfs
      o: bind
      device: ${PATH_CONFIG}

networks:
  net:
    external: true